# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [ push ]

jobs:
    build-and-bublish:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 15.x ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup git user
                run: |
                    git config --global user.email "a.khod@bk.ru"
                    git config --global user.name "Schirbak"
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
                    always-auth: true
            -   name: Install packages
                run: yarn install
            -   name: Lint
                run: yarn lint:check
            -   name: Build
                run: yarn build
            -   name: Bump version & publish to npm
                if: contains('refs/heads/main', github.ref)
                run: |
                    echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
                    yarn release
            -   name: Push
                if: contains('refs/heads/main', github.ref)
                run: git push --follow-tags origin ${{ github.ref }}
            -   name: Publish
                if: contains('refs/heads/main', github.ref)
                run: yarn publish
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
