# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [ push ]

jobs:
    build-and-bublish:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 15.x ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -   name: Install packages
                run: yarn install
            -   name: Lint
                run: yarn lint:check
            -   name: Build
                run: yarn build
            -   name: Bump version & publish to npm
                if: contains('refs/heads/master', github.ref)
                run: |
                    echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
                    yarn release
                    yarn publish
            -   name: Push
                if: contains('refs/heads/master', github.ref)
                uses: ad-m/github-push-action@master
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    branch: ${{ github.ref }}
